//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkMate.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkMate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wechseln.
        /// </summary>
        public static string changeprofile_button {
            get {
                return ResourceManager.GetString("changeprofile_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandanten.
        /// </summary>
        public static string clients_header {
            get {
                return ResourceManager.GetString("clients_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandanten Liste.
        /// </summary>
        public static string clients_list {
            get {
                return ResourceManager.GetString("clients_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string clients_modify {
            get {
                return ResourceManager.GetString("clients_modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Name.
        /// </summary>
        public static string clients_modify_name {
            get {
                return ResourceManager.GetString("clients_modify_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu anlegen.
        /// </summary>
        public static string clients_new {
            get {
                return ResourceManager.GetString("clients_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Mandanten.
        /// </summary>
        public static string clients_new_name {
            get {
                return ResourceManager.GetString("clients_new_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anstehende Temine.
        /// </summary>
        public static string clients_upcoming_jobs {
            get {
                return ResourceManager.GetString("clients_upcoming_jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string close_button {
            get {
                return ResourceManager.GetString("close_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandant.
        /// </summary>
        public static string general_client_text {
            get {
                return ResourceManager.GetString("general_client_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen.
        /// </summary>
        public static string general_create_text {
            get {
                return ResourceManager.GetString("general_create_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string general_date_text {
            get {
                return ResourceManager.GetString("general_date_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string general_delete_button {
            get {
                return ResourceManager.GetString("general_delete_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string general_description_text {
            get {
                return ResourceManager.GetString("general_description_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string general_details_text {
            get {
                return ResourceManager.GetString("general_details_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erledigt.
        /// </summary>
        public static string general_done_description {
            get {
                return ResourceManager.GetString("general_done_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erledigt am.
        /// </summary>
        public static string general_done_text {
            get {
                return ResourceManager.GetString("general_done_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fällig am.
        /// </summary>
        public static string general_due_text {
            get {
                return ResourceManager.GetString("general_due_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauer.
        /// </summary>
        public static string general_duration_text {
            get {
                return ResourceManager.GetString("general_duration_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string general_id_text {
            get {
                return ResourceManager.GetString("general_id_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgabe.
        /// </summary>
        public static string general_job_text {
            get {
                return ResourceManager.GetString("general_job_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string general_modify_button {
            get {
                return ResourceManager.GetString("general_modify_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string general_name_text {
            get {
                return ResourceManager.GetString("general_name_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen.
        /// </summary>
        public static string general_search_text {
            get {
                return ResourceManager.GetString("general_search_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string general_status_text {
            get {
                return ResourceManager.GetString("general_status_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgabe löschen.
        /// </summary>
        public static string jobs_delete_button {
            get {
                return ResourceManager.GetString("jobs_delete_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgabe erledigt.
        /// </summary>
        public static string jobs_done_button {
            get {
                return ResourceManager.GetString("jobs_done_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgaben.
        /// </summary>
        public static string jobs_header {
            get {
                return ResourceManager.GetString("jobs_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufgaben Liste.
        /// </summary>
        public static string jobs_list {
            get {
                return ResourceManager.GetString("jobs_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erledigte Aufgaben aneigen.
        /// </summary>
        public static string jobs_list_filter_done {
            get {
                return ResourceManager.GetString("jobs_list_filter_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nur überfällige Aufgaben anzeigen.
        /// </summary>
        public static string jobs_list_filter_overdue {
            get {
                return ResourceManager.GetString("jobs_list_filter_overdue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Aufgabe.
        /// </summary>
        public static string jobs_new {
            get {
                return ResourceManager.GetString("jobs_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeit löschen.
        /// </summary>
        public static string jobs_time_delete {
            get {
                return ResourceManager.GetString("jobs_time_delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende.
        /// </summary>
        public static string jobs_time_end {
            get {
                return ResourceManager.GetString("jobs_time_end", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string jobs_time_start {
            get {
                return ResourceManager.GetString("jobs_time_start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesamtzeit: .
        /// </summary>
        public static string jobs_time_total {
            get {
                return ResourceManager.GetString("jobs_time_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beenden.
        /// </summary>
        public static string quit_button {
            get {
                return ResourceManager.GetString("quit_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string save_button {
            get {
                return ResourceManager.GetString("save_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notizen hinzufügen....
        /// </summary>
        public static string status_notes_add_text {
            get {
                return ResourceManager.GetString("status_notes_add_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeiten.
        /// </summary>
        public static string times_header {
            get {
                return ResourceManager.GetString("times_header", resourceCulture);
            }
        }
    }
}
